name: Promote to Production

concurrency:
  # No parallel runs allowed
  group: promote-production
  # Queue runs behind each other so each change is applied independently.
  cancel-in-progress: false

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  get-image-tag:
    if: github.ref == 'refs/heads/main' # Only run on main
    runs-on: ubuntu-latest
    environment: production
    outputs:
      image_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .

      - name: Get image tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  deploy:
    if: github.ref == 'refs/heads/main' # Only run on main, not strictly necessary but for safety
    uses: ./.github/workflows/deploy.yml
    needs: get-image-tag
    with:
      environment: production
      image_tag: ${{ needs.get-image-tag.outputs.image_tag }}
